### ISSUE TITLE
Max Audio Files

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#10]
## Environment
Windows 10

## Bug
When selecting audio files, the file dialog max's at around 500 audio files. This could be file size or file count based.

## Expected Behavior
System should alert the user if not all selected audio files are used.

**Comment by atruskie** [comment]
https://stackoverflow.com/questions/15851751/what-is-the-max-number-of-files-to-select-in-an-html5-multiple-file-input

So what I'd suggest here is allowing a user to "Choose a folder" rather than requiring them to choose files. We quite often have more than 500 files that need to be processed. Choosing a folder should also allow us to iterate through the File objects which will side-step the long loading problem you demonstrated.

I'm not sure you'll be able to detect if less than the number of selected files are pulled in?

Also, AP.exe will gain the functionality to process a folder as well so that should limit the work required by us.

**Comment by Allcharles** [comment]
Problem is fixed, it's a little annoying to select a folder when one file is needed for analysis. Could be a potential update to reduce this annoyance

Fixed in e9e4628600370ac47021c188c6b018a64b82792d

**Comment by atruskie** [comment]
@Allcharles please cross-link commits with issues https://help.github.com/en/articles/closing-issues-using-keywords

Please add/edit this thread to include the commit hash where this was fixed

**Comment by atruskie** [comment]
Also, I'm trying out your fix.

Let's keep the choice to choose single files.

- One option to "Choose files (maximum 100)" 
- and another (exclusive) option to "Choose a folder"
